"use client";

import React, { useEffect, useRef, useMemo, useState } from "react";
import { Highlight, themes } from "prism-react-renderer";
import { useTheme } from "next-themes";
import { useTutorialStore } from "../store/useTutorialStore";
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { FileCode, FileText, FileJson, Copy, Check } from "lucide-react";

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

const MOCK_FILES: Record<string, string> = {
  "main.go": `// Package main starts the application
package main

import (
	"log"
	"os"
)

func handleDeferError(err error) {
	if err != nil {
		log.Println(err)
	}
}

func main() {
	a := &App{}
	err := a.Initialize(
-		"localhost", // postgres host
+		"postgres", // Change localhost to postgres when using Docker
		"postgres", // username
		"password", // password
		"postgres") // db_name

	if err != nil {
		log.Printf("Failed to initialize app %s", err)
		os.Exit(1)
	}

	log.Printf("😃 Connected to 8010 port !!")

	a.Run(":8010")
}`,
  "test-1.yml": `# Generated by Keploy (3.3.72)
version: api.keploy.io/v1beta1
kind: Http
name: test-1
spec:
  metadata: {}
  req:
    method: POST
    proto_major: 1
    proto_minor: 1
    url: http://localhost:8010/product
    header:
      Accept: '*/*'
      Content-Length: "31"
      Content-Type: application/json
      Host: localhost:8010
      User-Agent: curl/8.7.1
    body: '{"name":"Bubbles","price": 123}'
    timestamp: 2026-04-13T12:59:13.920437886Z
  resp:
    status_code: 201
    header:
      Content-Length: "37"
      Content-Type: application/json
      Date: Mon, 13 Apr 2026 12:59:13 GMT
    body: '{"id":1,"name":"Bubbles","price":123}'
    status_message: Created
    proto_major: 0
    proto_minor: 0
    timestamp: 2026-04-13T12:59:13.929830969Z
  objects: []
  assertions:
    noise:
      header.Date: []
  created: 1776085153
  app_port: 8010
curl: |-
  curl --request POST \
    --url http://localhost:8010/product \
    --header 'Accept: */*' \
    --header 'Content-Type: application/json' \
    --header 'Host: localhost:8010' \
    --header 'User-Agent: curl/8.7.1' \
    --data "{\"name\":\"Bubbles\",\"price\": 123}"`,
  "test-2.yml": `# Generated by Keploy (3.3.72)
version: api.keploy.io/v1beta1
kind: Http
name: test-2
spec:
  metadata: {}
  req:
    method: GET
    proto_major: 1
    proto_minor: 1
    url: http://localhost:8010/products
    header:
      Accept: '*/*'
      Host: localhost:8010
      User-Agent: curl/8.7.1
    timestamp: 2026-04-13T13:00:17.720437886Z
  resp:
    status_code: 200
    header:
      Content-Type: application/json
      Date: Mon, 13 Apr 2026 13:00:17 GMT
    body: '[{"id":1,"name":"Bubbles","price":123}]'
    status_message: OK
    proto_major: 0
    proto_minor: 0
    timestamp: 2026-04-13T13:00:17.732830969Z
  objects: []
  assertions:
    noise:
      header.Date: []
  created: 1776085217
  app_port: 8010`,
  "mock.yaml": `# Generated by Keploy (3.3.72)
version: api.keploy.io/v1beta1
kind: DNS
name: mock-0
spec:
    metadata:
        name: DNS
        qtype: AAAA
        type: config
    request:
        name: postgres.
        qtype: 28
        qclass: 1
    response:
        rcode: 0
        authoritative: false
        recursionAvailable: true
        truncated: false
    reqTimestampMock: 2026-04-13T12:59:13.923109261Z
    resTimestampMock: 2026-04-13T12:59:13.924133594Z
---
version: api.keploy.io/v1beta1
kind: DNS
name: mock-1
spec:
    metadata:
        name: DNS
        qtype: A
        type: config
    request:
        name: postgres.
        qtype: 1
        qclass: 1
    response:
        rcode: 0
        authoritative: false
        recursionAvailable: true
        truncated: false
        answers:
            - "postgres.\t600\tIN\tA\t172.24.0.2"
    reqTimestampMock: 2026-04-13T12:59:13.923109219Z
    resTimestampMock: 2026-04-13T12:59:13.924230969Z
---
version: api.keploy.io/v1beta1
kind: PostgresV2
name: mock-2
spec:
    metadata:
        connID: "0"
        type: config
    requests:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 98
                        packet_id: ""
                    packet_type: StartupMessage
                  message:
                    protocolversion: 196608
                    parameters:
                        client_encoding: UTF8
                        database: postgres
                        datestyle: ISO, MDY
                        extra_float_digits: "2"
                        user: postgres
        - message:
            packets:
                - header:
                    header:
                        payload_length: 36
                        packet_id: p
                    packet_type: PasswordMessage
                  message:
                    password: md5cb173b002d8fe7055b0ef65b8f4be20c
    responses:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 8
                        packet_id: R
                    packet_type: AuthenticationMD5Password
                  message:
                    salt: [254, 183, 185, 51]
        - message:
            packets:
                - header:
                    header:
                        payload_length: 4
                        packet_id: R
                    packet_type: AuthenticationOk
                  message: {}
                - header:
                    header:
                        payload_length: 18
                        packet_id: S
                    packet_type: ParameterStatus
                  message:
                    name: application_name
                    value: ""
                - header:
                    header:
                        payload_length: 21
                        packet_id: S
                    packet_type: ParameterStatus
                  message:
                    name: client_encoding
                    value: UTF8
                - header:
                    header:
                        payload_length: 19
                        packet_id: S
                    packet_type: ParameterStatus
                  message:
                    name: DateStyle
                    value: ISO, MDY
                - header:
                    header:
                        payload_length: 21
                        packet_id: S
                    packet_type: ParameterStatus
                  message:
                    name: integer_datetimes
                    value: "on"
                - header:
                    header:
                        payload_length: 23
                        packet_id: S
                    packet_type: ParameterStatus
                  message:
                    name: IntervalStyle
                    value: postgres
                - header:
                    header:
                        payload_length: 16
                        packet_id: S
                    packet_type: ParameterStatus
                  message:
                    name: is_superuser
                    value: "on"
                - header:
                    header:
                        payload_length: 21
                        packet_id: S
                    packet_type: ParameterStatus
                  message:
                    name: server_encoding
                    value: UTF8
                - header:
                    header:
                        payload_length: 45
                        packet_id: S
                    packet_type: ParameterStatus
                  message:
                    name: server_version
                    value: 10.5 (Debian 10.5-2.pgdg90+1)
                - header:
                    header:
                        payload_length: 31
                        packet_id: S
                    packet_type: ParameterStatus
                  message:
                    name: session_authorization
                    value: postgres
                - header:
                    header:
                        payload_length: 31
                        packet_id: S
                    packet_type: ParameterStatus
                  message:
                    name: standard_conforming_strings
                    value: "on"
                - header:
                    header:
                        payload_length: 13
                        packet_id: S
                    packet_type: ParameterStatus
                  message:
                    name: TimeZone
                    value: UTC
                - header:
                    header:
                        payload_length: 8
                        packet_id: K
                    packet_type: BackendKeyData
                  message:
                    process_id: 68
                    secret_key: 1530667659
                - header:
                    header:
                        payload_length: 1
                        packet_id: Z
                    packet_type: ReadyForQuery
                  message:
                    txstatus: 73
    reqtimestampmock: 2026-04-13T12:59:13.925062594Z
    restimestampmock: 2026-04-13T12:59:13.928221094Z
connectionId: "0"
---
version: api.keploy.io/v1beta1
kind: PostgresV2
name: mock-3
spec:
    metadata:
        connID: "0"
        query: INSERT INTO products(name, price) VALUES($1, $2) RETURNING id
        requestOperation: Parse
        responseOperation: ParseComplete
        type: mocks
    requests:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 65
                        packet_id: P
                    packet_type: Parse
                  message:
                    name: ""
                    query: INSERT INTO products(name, price) VALUES($1, $2) RETURNING id
                    parameter_oids: []
    responses:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 0
                        packet_id: "1"
                    packet_type: ParseComplete
                  message: {}
    reqtimestampmock: 2026-04-13T12:59:13.928350927Z
    restimestampmock: 2026-04-13T12:59:13.928853594Z
connectionId: "0"
---
version: api.keploy.io/v1beta1
kind: PostgresV2
name: mock-4
spec:
    metadata:
        connID: "0"
        describe_object_type: S
        describe_result_shape: rowdesc
        query: INSERT INTO products(name, price) VALUES($1, $2) RETURNING id
        requestOperation: Describe
        responseOperation: ParameterDescription
        type: mocks
    requests:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 2
                        packet_id: D
                    packet_type: Describe
                  message:
                    object_type: 83
                    name: ""
    responses:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 10
                        packet_id: t
                    packet_type: ParameterDescription
                  message:
                    parameteroids:
                        - 25
                        - 1700
                - header:
                    header:
                        payload_length: 23
                        packet_id: T
                    packet_type: RowDescription
                  message:
                    fields:
                        - field_name: id
                          table_oid: 16386
                          table_attribute_number: 1
                          data_type_oid: 23
                          data_type_size: 4
                          type_modifier: -1
                          format: 0
    reqtimestampmock: 2026-04-13T12:59:13.928350927Z
    restimestampmock: 2026-04-13T12:59:13.928853594Z
connectionId: "0"
---
version: api.keploy.io/v1beta1
kind: PostgresV2
name: mock-5
spec:
    metadata:
        connID: "0"
        requestOperation: Sync
        responseOperation: ReadyForQuery
        type: mocks
    requests:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 0
                        packet_id: S
                    packet_type: Sync
                  message: {}
    responses:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 1
                        packet_id: Z
                    packet_type: ReadyForQuery
                  message:
                    txstatus: 73
    reqtimestampmock: 2026-04-13T12:59:13.928350927Z
    restimestampmock: 2026-04-13T12:59:13.928853594Z
connectionId: "0"
---
version: api.keploy.io/v1beta1
kind: PostgresV2
name: mock-6
spec:
    metadata:
        connID: "0"
        query: INSERT INTO products(name, price) VALUES($1, $2) RETURNING id
        requestOperation: Bind
        responseOperation: BindComplete
        type: mocks
    requests:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 28
                        packet_id: B
                    packet_type: Bind
                  message:
                    parameters: [[66, 117, 98, 98, 108, 101, 115], [49, 50, 51]]
                    result_format_codes: [1]
    responses:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 0
                        packet_id: "2"
                    packet_type: BindComplete
                  message: {}
    reqtimestampmock: 2026-04-13T12:59:13.928977886Z
    restimestampmock: 2026-04-13T12:59:13.929664969Z
connectionId: "0"
---
version: api.keploy.io/v1beta1
kind: PostgresV2
name: mock-7
spec:
    metadata:
        connID: "0"
        query: INSERT INTO products(name, price) VALUES($1, $2) RETURNING id
        requestOperation: Execute
        responseOperation: DataRows
        type: mocks
    requests:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 5
                        packet_id: E
                    packet_type: Execute
                  message: {}
    responses:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 10
                        packet_id: 1*D
                    packet_type: DataRows
                  message:
                    rows_values: [['b64:AAAAAQ==']]
                - header:
                    header:
                        payload_length: 11
                        packet_id: C
                    packet_type: CommandComplete
                  message:
                    command_tag_type: INSERT 0 1
    reqtimestampmock: 2026-04-13T12:59:13.928977886Z
    restimestampmock: 2026-04-13T12:59:13.929664969Z
connectionId: "0"
---
version: api.keploy.io/v1beta1
kind: PostgresV2
name: mock-8
spec:
    metadata:
        connID: "0"
        requestOperation: Sync
        responseOperation: ReadyForQuery
        type: mocks
    requests:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 0
                        packet_id: S
                    packet_type: Sync
                  message: {}
    responses:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 1
                        packet_id: Z
                    packet_type: ReadyForQuery
                  message:
                    txstatus: 73
    reqtimestampmock: 2026-04-13T12:59:13.928977886Z
    restimestampmock: 2026-04-13T12:59:13.929664969Z
connectionId: "0"
---
version: api.keploy.io/v1beta1
kind: PostgresV2
name: mock-9
spec:
    metadata:
        connID: "0"
        query: SELECT id, name, price FROM products LIMIT $1 OFFSET $2
        requestOperation: Parse
        responseOperation: ParseComplete
        type: mocks
    requests:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 60
                        packet_id: P
                    packet_type: Parse
                  message:
                    name: ""
                    query: SELECT id, name, price FROM products LIMIT $1 OFFSET $2
                    parameter_oids: []
    responses:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 0
                        packet_id: "1"
                    packet_type: ParseComplete
                  message: {}
    reqtimestampmock: 2026-04-13T13:00:17.729401012Z
    restimestampmock: 2026-04-13T13:00:17.730216721Z
connectionId: "0"
---
version: api.keploy.io/v1beta1
kind: PostgresV2
name: mock-10
spec:
    metadata:
        connID: "0"
        describe_object_type: S
        describe_result_shape: rowdesc
        query: SELECT id, name, price FROM products LIMIT $1 OFFSET $2
        requestOperation: Describe
        responseOperation: ParameterDescription
        type: mocks
    requests:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 2
                        packet_id: D
                    packet_type: Describe
                  message:
                    object_type: 83
                    name: ""
    responses:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 10
                        packet_id: t
                    packet_type: ParameterDescription
                  message:
                    parameteroids:
                        - 20
                        - 20
                - header:
                    header:
                        payload_length: 70
                        packet_id: T
                    packet_type: RowDescription
                  message:
                    fields:
                        - field_name: id
                          table_oid: 16386
                          table_attribute_number: 1
                          data_type_oid: 23
                          data_type_size: 4
                          type_modifier: -1
                          format: 0
                        - field_name: name
                          table_oid: 16386
                          table_attribute_number: 2
                          data_type_oid: 25
                          data_type_size: -1
                          type_modifier: -1
                          format: 0
                        - field_name: price
                          table_oid: 16386
                          table_attribute_number: 3
                          data_type_oid: 1700
                          data_type_size: -1
                          type_modifier: 655366
                          format: 0
    reqtimestampmock: 2026-04-13T13:00:17.729401012Z
    restimestampmock: 2026-04-13T13:00:17.730216721Z
connectionId: "0"
---
version: api.keploy.io/v1beta1
kind: PostgresV2
name: mock-11
spec:
    metadata:
        connID: "0"
        requestOperation: Sync
        responseOperation: ReadyForQuery
        type: mocks
    requests:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 0
                        packet_id: S
                    packet_type: Sync
                  message: {}
    responses:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 1
                        packet_id: Z
                    packet_type: ReadyForQuery
                  message:
                    txstatus: 73
    reqtimestampmock: 2026-04-13T13:00:17.729401012Z
    restimestampmock: 2026-04-13T13:00:17.730216721Z
connectionId: "0"
---
version: api.keploy.io/v1beta1
kind: PostgresV2
name: mock-12
spec:
    metadata:
        connID: "0"
        query: SELECT id, name, price FROM products LIMIT $1 OFFSET $2
        requestOperation: Bind
        responseOperation: BindComplete
        type: mocks
    requests:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 25
                        packet_id: B
                    packet_type: Bind
                  message:
                    parameters: [[49, 48], [48]]
                    result_format_codes: [1, 0, 0]
    responses:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 0
                        packet_id: "2"
                    packet_type: BindComplete
                  message: {}
    reqtimestampmock: 2026-04-13T13:00:17.730394346Z
    restimestampmock: 2026-04-13T13:00:17.731157179Z
connectionId: "0"
---
version: api.keploy.io/v1beta1
kind: PostgresV2
name: mock-13
spec:
    metadata:
        connID: "0"
        query: SELECT id, name, price FROM products LIMIT $1 OFFSET $2
        requestOperation: Execute
        responseOperation: DataRows
        type: mocks
    requests:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 5
                        packet_id: E
                    packet_type: Execute
                  message: {}
    responses:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 31
                        packet_id: 1*D
                    packet_type: DataRows
                  message:
                    rows_values: [['b64:AAAAAQ==', Bubbles, "123.00"]]
                - header:
                    header:
                        payload_length: 9
                        packet_id: C
                    packet_type: CommandComplete
                  message:
                    command_tag_type: SELECT 1
    reqtimestampmock: 2026-04-13T13:00:17.730394346Z
    restimestampmock: 2026-04-13T13:00:17.731157179Z
connectionId: "0"
---
version: api.keploy.io/v1beta1
kind: PostgresV2
name: mock-14
spec:
    metadata:
        connID: "0"
        requestOperation: Sync
        responseOperation: ReadyForQuery
        type: mocks
    requests:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 0
                        packet_id: S
                    packet_type: Sync
                  message: {}
    responses:
        - message:
            packets:
                - header:
                    header:
                        payload_length: 1
                        packet_id: Z
                    packet_type: ReadyForQuery
                  message:
                    txstatus: 73
    reqtimestampmock: 2026-04-13T13:00:17.730394346Z
    restimestampmock: 2026-04-13T13:00:17.731157179Z
connectionId: "0"`
};

const FileIcon = ({ filename, className }: { filename: string; className?: string }) => {
  if (filename.endsWith(".go")) return <FileCode className={className} />;
  if (filename.endsWith(".yml") || filename.endsWith(".yaml")) return <FileText className={className} />;
  return <FileJson className={className} />;
};

export const CodePane = () => {
  const { theme } = useTheme();
  const { activeFile, activeLineRange, activeCodeSnippet, setActiveCode } = useTutorialStore();
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const activeLineRef = useRef<HTMLDivElement>(null);
  const [copied, setCopied] = useState(false);

  const fileList = Object.keys(MOCK_FILES);
  const currentFile = activeFile || fileList[0];

  const code = useMemo(() => {
    // If we have a matching mock file, use it
    if (MOCK_FILES[currentFile]) return MOCK_FILES[currentFile];
    
    // Otherwise fall back to snippet
    return activeCodeSnippet || "// No code snippet selected";
  }, [currentFile, activeCodeSnippet]);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const language = useMemo(() => {
    if (currentFile.endsWith(".go")) return "go";
    if (currentFile.endsWith(".yml") || currentFile.endsWith(".yaml")) return "yaml";
    return "javascript";
  }, [currentFile]);

  useEffect(() => {
    if (activeLineRange && activeLineRef.current) {
      activeLineRef.current.scrollIntoView({
        behavior: "smooth",
        block: "center",
      });
    }
  }, [activeLineRange, activeFile]);

  return (
    <div className="h-full flex flex-col bg-zinc-50 dark:bg-[#050505] overflow-hidden group/pane relative">
      {/* File Tabs Navigation */}
      <div className="flex items-center justify-between pr-2 border-b border-zinc-200 dark:border-zinc-800 bg-zinc-100/50 dark:bg-zinc-900/50">
        <div className="flex items-center gap-1 px-3 py-2 overflow-x-auto no-scrollbar">
          {fileList.map((fileName) => {
            const isActive = currentFile === fileName;
            return (
              <button
                key={fileName}
                onClick={() => setActiveCode(fileName)}
                className={cn(
                  "flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[12px] font-medium transition-all whitespace-nowrap",
                  isActive 
                    ? "bg-white dark:bg-zinc-800 text-[#FF914D] shadow-sm border border-zinc-200 dark:border-zinc-700" 
                    : "text-zinc-500 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-200"
                )}
              >
                <FileIcon filename={fileName} className="h-3.5 w-3.5" />
                {fileName}
              </button>
            );
          })}
        </div>

        <button
          onClick={handleCopy}
          className="p-1.5 rounded-md text-zinc-400 hover:text-[#FF914D] hover:bg-white dark:hover:bg-zinc-800 transition-all opacity-0 group-hover/pane:opacity-100"
          title="Copy code"
        >
          {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
        </button>
      </div>      
      <div 
        ref={scrollContainerRef}
        className="flex-1 overflow-x-hidden overflow-y-auto custom-scrollbar"
      >
        <Highlight
          theme={theme === "light" ? themes.github : themes.vsDark}
          code={code}
          language={language}
        >
          {({ className, style, tokens, getLineProps, getTokenProps }) => (
            <pre className={cn(className, "bg-transparent py-4 m-0 font-mono text-[13px] leading-relaxed whitespace-pre-wrap break-words")} style={style}>
              {tokens.map((line, i) => {
                const lineNumber = i + 1;
                const isActive = activeLineRange && currentFile === activeFile
                  ? lineNumber >= activeLineRange[0] && lineNumber <= activeLineRange[1]
                  : false;
                
                const isFirstActiveLine = activeLineRange && lineNumber === activeLineRange[0];
                
                // Detect diff lines
                const lineText = line.map(t => t.content).join("");
                const isRemoval = lineText.startsWith("-");
                const isAddition = lineText.startsWith("+");

                return (
                  <div
                    key={i}
                    {...getLineProps({ line })}
                    ref={isFirstActiveLine ? activeLineRef : null}
                    className={cn(
                      "flex px-4 py-0.5 transition-colors duration-200 border-l-2",
                      isActive ? "bg-orange-500/10 border-[#FF914D]" : "border-transparent",
                      isRemoval && "bg-red-500/10 border-red-500 diff-remove",
                      isAddition && "bg-green-500/10 border-green-500 diff-add"
                    )}
                  >
                    <span className="select-none pr-4 text-right text-zinc-600 dark:text-zinc-700 w-10 shrink-0">
                      {lineNumber}
                    </span>
                    <span className="whitespace-pre-wrap break-all flex items-start">
                      {(isRemoval || isAddition) && (
                        <span className="diff-symbol shrink-0">
                          {isRemoval ? "-" : "+"}
                        </span>
                      )}
                      <span className="flex-1">
                        {line.map((token, key) => {
                          // If it's the first token of a diff line, strip the prefix from the token content
                          // since we're now rendering it separately in diff-symbol
                          if (key === 0 && (isRemoval || isAddition)) {
                            const content = token.content.substring(1);
                            return <span key={key} {...getTokenProps({ token: { ...token, content } })} />;
                          }
                          return <span key={key} {...getTokenProps({ token })} />;
                        })}
                      </span>
                    </span>
                  </div>
                );
              })}
            </pre>
          )}
        </Highlight>
      </div>
    </div>
  );
};
